name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: install 
        run: npm install

      - name: lint
        run: npm run eslint

      - name: test
        run: npm run test

      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
           with:
          config: pageLoadTimeout=100000,baseUrl=http://localhost:5000

      if: ${{ github.event_name == 'push' }}
      - name: deploy
        uses: actions/checkout@v2
        uses: akhileshns/heroku-deploy@v3.8.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "muikku-pokedex"
          heroku_email: "markus.muinonen@gmail.com"
          healthcheck: "https://muikku-pokedex.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true